"""Updated SellerModel

Revision ID: 19b2e038a6ad
Revises: d78e0ea53bd6
Create Date: 2024-08-14 08:55:16.649766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b2e038a6ad'
down_revision = 'd78e0ea53bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('sellers', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('sellers', sa.Column('preferences', sa.String(length=255), nullable=True))
    op.add_column('sellers', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.drop_column('sellers', 'hashed_password')
    op.drop_column('sellers', 'preferences')
    op.drop_column('sellers', 'profile_picture')
    op.drop_column('sellers', 'rating')
    op.drop_column('sellers', 'email')
    # ### end Alembic commands ###
