"""Added verification_expiration

Revision ID: 2e5773159766
Revises: d4c7f7c47384
Create Date: 2024-10-08 12:36:08.154688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5773159766'
down_revision = 'd4c7f7c47384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expiration')
    # ### end Alembic commands ###
