"""Added jwt

Revision ID: 7634fdbd629c
Revises: 7282b99da864
Create Date: 2024-10-06 14:51:13.760958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7634fdbd629c'
down_revision = '7282b99da864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt_token_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt_token_key')
    # ### end Alembic commands ###
