"""Regenerate users table

Revision ID: 908d8c67976a
Revises: 8a312b84383c
Create Date: 2024-09-07 09:30:58.467321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908d8c67976a'
down_revision = '8a312b84383c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('preferences', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=35), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'customer_events', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'customer_notes', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'staff_notification_recipients', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_groups', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'wishlists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'staff_notification_recipients', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'customer_notes', type_='foreignkey')
    op.drop_constraint(None, 'customer_events', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
