"""Add review relationship to VendorModel

Revision ID: bee46c8490d0
Revises: 2828836248b3
Create Date: 2024-08-05 12:58:46.419160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bee46c8490d0'
down_revision = '2828836248b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add vendor_id column to products table if it does not exist
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vendor', 'vendors', ['vendor_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop vendor_id column from products table
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('fk_vendor', type_='foreignkey')
        batch_op.drop_column('vendor_id')
    # ### end Alembic commands ###
