"""password_last_update

Revision ID: d4c7f7c47384
Revises: 7634fdbd629c
Create Date: 2024-10-06 15:00:38.058627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c7f7c47384'
down_revision = '7634fdbd629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_last_updated')
    # ### end Alembic commands ###
