"""Add additional fields to User model

Revision ID: dcc829334c5a
Revises: 0be6fe9a7af8
Create Date: 2024-08-03 08:56:18.339494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc829334c5a'
down_revision = '0be6fe9a7af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='t'))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True, server_default='user'))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True, server_default='f'))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_last_updated', sa.DateTime(), nullable=True, server_default=sa.func.now()))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('account_locked', sa.Boolean(), nullable=True, server_default='f'))
    op.add_column('users', sa.Column('backup_codes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'password_last_updated')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'account_locked')
    op.drop_column('users', 'backup_codes')
    # ### end Alembic commands ###
